train_selfsup_mr:
    name: [KINETIX]
    path: [/data/vidar/KinetixDataset]
    splits: [kinetix_dataset.txt]
    augmentation:
        jittering: [0.2, 0.2, 0.2, 0.05]
        resize: [192, 640]
    dataloader:
        batch_size: 1
        pin_memory: False
        num_workers: 4
    context: [-1,1]
    labels: []
    cameras: [[0]]
    single_intrinsics: [False]
    repeat: [1]