train_selfsup_mr:
    name: [Minimal] # Need to be the correct name ! The MinimalDataset class is retrieved from it.
    path: [/data/vidar/MinimalDataset]
    split: [minimal_dataset.txt]
    augmentation:
        jittering: [0.2,0.2,0.2,0.05]
        resize: [192,640]
    dataloader:
        batch_size: 8
        pin_memory: False
        num_workers: 4
    context: [-1,1]
    labels: []
    cameras: [[0]]
    single_intrinsics: [True]
    repeat: [1]
validation_mr:
    name: [Minimal]
    path: [/data/vidar/MinimalDataset]
    split: [minimal_dataset.txt]
    augmentation:
        jittering: [0.2,0.2,0.2,0.05]
        resize: [192,640]
    dataloader:
        batch_size: 8
        pin_memory: False
        num_workers: 4
    context: []
    labels: []
    cameras: [[0]]
    single_intrinsics: [True]
    depth_type: [velodyne] 
