train_selfsup_mr:
    name: [Overfit] # Need to be the correct name ! The OverfitDataset class is retrieved from it.
    path: [/data/vidar/OverfitDataset]
    split: [overfit_dataset_mini.txt]
    # augmentation:
    #     resize: [480,640]
    dataloader:
        batch_size: 1
        pin_memory: False
        num_workers: 4
    context: [-1,1]
    labels: []
    cameras: [[0]]
    single_intrinsics: [True]
    repeat: [10]
    depth_type: [velodyne]
validation_mr:
    name: [Overfit]
    path: [/data/vidar/OverfitDataset]
    split: [overfit_val_dataset.txt]
    # augmentation:
    #     resize: [480,640]
    dataloader:
        batch_size: 1
        pin_memory: False
        num_workers: 4
    context: []
    labels: []
    cameras: [[0]]
    single_intrinsics: [True]
    depth_type: [velodyne] 
