train_selfsup_mr:
    name: [Thomas] # Need to be the correct name ! The ThomasDataset class is retrieved from it.
    path: [/data/vidar/ThomasDataset]
    split: [walk_person_idle/640x360-30fps.txt]
    # augmentation:
    #     resize: [480,640]
    dataloader:
        batch_size: 1
        pin_memory: False
        num_workers: 4
    context: [-1,1]
    labels: []
    cameras: [[0]]
    single_intrinsics: [True]
    repeat: [3]
    depth_type: [velodyne]
validation_mr:
    name: [Thomas]
    path: [/data/vidar/ThomasDataset]
    split: [walk_person_idle/640x360-30fps_val.txt]
    # augmentation:
    #     resize: [480,640]
    dataloader:
        batch_size: 1
        pin_memory: False
        num_workers: 4
    context: []
    labels: []
    cameras: [[0]]
    single_intrinsics: [True]
    depth_type: [velodyne] 
